### ISSUE TITLE
Improve coverage

### ISSUE THREAD

**Issue by ghost** [splunk/addonfactory-solutions-library-python#121]
Files to work on:

- [ ] acl.py
- [ ] conf_manager.py
- [ ] credentials.py
- [x] file_monitor.py #127 
- [ ] hec_config.py
- [ ] log.py
- [x] net_utils.py #120 
- [ ] orphan_process_monitor.py
- [x] pattern.py
- [ ] server_info.py
- [ ] splunk_rest_client.py
- [ ] splunkenv.py
- [x] time_parser.py #120
- [ ] timer_queue.py
- [ ] user_access.py
- [ ] utils.py
- [x] modular_input.checkpointer #122
- [ ] modular_input.event
- [ ] modular_input.event_writer
- [ ] modular_input.modular_input
